### ISSUE TITLE
Multiple signs of one file

### ISSUE THREAD

**Issue by zim32** [dstucrypt/agent#13]
Hy. Thanks for your work. Great job!

I have a question - is it possible to make multiple signs for one file? F.e. I have some doc that needs to be signed by three persons.
Thanks

**Comment by muromec** [comment]
Hej zim32,

Yes, you can make multiply signatures on a same file, by calling agent multiply times.

It is possible to do so in one call with some changes to agent app, which you are welcome to send as a PR.

**Comment by zim32** [comment]
Ok I will try. So I just need to pass already signed file and all params stay the same? I would like to help but for me all this stuff with all this crwzy chipers and so on is so new and unknown..

**Comment by muromec** [comment]
Yes, you just sign already signed file and that's it. Be sure to use `--no-tax` when you sign normal tax and not files to be emailed to tax office.
