### ISSUE TITLE
Privatbank jks - internal error

### ISSUE THREAD

**Issue by naduda** [dstucrypt/agent#17]
Підкажіть будь-ласка, що тут не так.
Тут https://dstucrypt.github.io/signerbox2/ все нормально.

![image](https://user-images.githubusercontent.com/4903808/103458045-fd53b580-4d0c-11eb-85ad-d2f011f3e1d8.png)

![image](https://user-images.githubusercontent.com/4903808/103458735-a6051380-4d13-11eb-87fe-5e7e1cfc7a25.png)

**Comment by muromec** [comment]
Додайде `--no-role` або `--role personal`.

**Comment by naduda** [comment]
Дякую, так працює. (Можливо це потрібно добавити в Readme десь ближче до прикладу :))
