### ISSUE TITLE
Error when npm install packages from package.json

### ISSUE THREAD

**Issue by oleksiyVeretiuk** [dstucrypt/agent#2]
When I try to install such packages: node-gf2m, node-gost89 I get this error 
node-gf2m@0.1.0 install: `node-gyp configure build`
In my opinion it is related to version of node or npm. So it will really helpful if you say what version of node and npm you have used.

**Comment by muromec** [comment]
That was build for old version of node. You can replace pure js versions of both, as updated in 635c191.

**Comment by muromec** [comment]
Actually, pure js version of both packages were used since f62b0dd anyway, that's just package.json file was not updated.

**Comment by oleksiyVeretiuk** [comment]
Okay. Thank you for answer.
