### ISSUE TITLE
Відсутній транспортний заголовок 'TRANSPORTABLE'

### ISSUE THREAD

**Issue by Tarasila** [dstucrypt/agent#23]
Добрий день. Викликаю програму за допомогою даної команди:

```
node index.js --sign --crypt .\user_data\STS_2019_2.cer ^
            --tsp all ^
            --key .\user_data\Key-6.dat:tectfom ^
            --cert .\user_data\certificate_sign.cer ^
            --cert .\user_data\certificate_agreement.cer ^
            --input .\user_data\24121010101017F1316602101969645310520212412.XML ^
            --output .\user_data\signed_data\24121010101017F1316602101969645310520212412.XML.signed ^
            --edrpou 1010101017 ^
            --email test@gmail.com ^
            --role personal 
```
У відповідь помилка: `Internal error`.

Якщо з попередньої команди забрати аргумент `email` – файл буде підписаним і зашифрованим, але без хедера і сигнатури `TRANSPORTABLE`. Підкажіть, будь ласка, в чому проблема.

----
Сертифікат STS_2019_2.cer беру тут: https://tax.gov.ua/elektronna-zvitnist/platnikam-podatkiv-pro/edina-adresa/
Тестовий ключ і сертифікати: Мирний

**Comment by nofikoff** [comment]
Тоже такая самая проблема, но не стал разбираться.
Подписал отчет в ручную через https://sign.diia.gov.ua/ с ключами МИРНОГО

**Comment by muromec** [comment]
Прівєтулі, пофікшено.
