### ISSUE TITLE
Розшифрування відповіді (повідомлення) з ДПС

### ISSUE THREAD

**Issue by Tarasila** [dstucrypt/agent#24]
Добрий день. Після виклику агента за допомогою команди:

```
node index.js --decrypt ^
            --key .\user_data\Key-6.dat:tectfom ^
            --input .\user_data\sfs_response\sfs_response_msg.encrypted ^
            --output .\user_data\sfs_response\unwrapped\sfs_response_msg.unwrapped ^
            --tsp all ^
            --ocsp strict ^
            --ca_path CACertificates.p7b 
```

програма відпрацьовує без помилки, але файл на виході `sfs_response_msg.unwrapped` ідентичний початковому `sfs_response_msg.encrypted`. Що я роблю не так?

---
CACertificates.p7b беру тут: `curl.exe --output CACertificates.p7b --url https://id.gov.ua/verify-widget/v20200922/Data/CACertificates.p7b`
Тестовий ключ і сертифікати: Мирний

**Comment by Tarasila** [comment]
Ось повідомлення:
[sfs_response_msg_unwrapped.txt](https://github.com/dstucrypt/agent/files/6561654/sfs_response_msg_unwrapped.txt)

**Comment by Tarasila** [comment]
@muromec, cпробував розшифрувати своє ж повідомлення - все працює, на виході сирий .xml. Можливо повідомлення з ДПС просто має інший порядок сигнатур?

**Comment by muromec** [comment]
Порішали ж да?

**Comment by Tarasila** [comment]
Так!
