### ISSUE TITLE
Підтвердження позначкою часу від АЦСК

### ISSUE THREAD

**Issue by RevanScript** [dstucrypt/agent#3]
Вітаю!

Потрібні додаткові дії? Чи фіча ще не реалізована?

```
Звертаємо Вашу увагу на те, що із набуттям чинності 07.11.2018 Закону України «Про електронні довірчі послуги» та відповідно до частини четвертої статті 26 цього закону, використання кваліфікованої електронної позначки часу для постійного зберігання електронних даних є обов’язковим.

Просимо звернутися до свого суб’єкта надання послуг електронного підпису із вимогою про приведення програмно-технічного комплексу у відповідність до норм законодавства.
```

**Comment by muromec** [comment]
Хєлоу,

Підтримка позначки часу (TSP) є в jkurwa (models/Message) та (examples/tsp), але її немає в консольному агенті.

Там не дуже складно - треба передати відповідь від tsp серверу в models/Message і все запрацює.

**Comment by RevanScript** [comment]
Ок, дякую за підсказку і в цілому за роботу над проектом!

**Comment by muromec** [comment]
Зараз повинно працювати.

**Comment by RevanScript** [comment]
Так, все супер. Дякую!

Один нюанс — назви функції відрізняються :)
[index.js:79](https://github.com/dstucrypt/agent/blob/8087546389b0ebde924ddbffc35db16c9b89f93a/index.js#L79)
[index.js:235](https://github.com/dstucrypt/agent/blob/8087546389b0ebde924ddbffc35db16c9b89f93a/index.js#L235)

**Comment by muromec** [comment]
упс. тяжко жити без тестів. тепер *точно* працює

**Comment by spyzp** [comment]
Во-первых, спасибо за вашу работу — отличные библиотеки и утилиты!

подскажите, пожалуйста, можно ли сделать "метку времени" не для данных, а для подписи, как требует ДФС в некоторых случаях... Вот выглядит ошибка: "Повідомлення не може містити позначку часу контента. Позначкою часу фіксується кваліфікований електронний підпис"
ссылаются на "атрибут signature-time-stamp відповідно до вимог ДСТУ ETSI EN 319 122-2:2016, IDT"

сделал ради эксперимента подпись библиотеками IIT (дико неудобными в использовании по сравнению с вашими)... 
действительно, есть разница.

проверил файлик подписанный ими:
Час підпису (підтверджено кваліфікованою позначкою часу для **підпису** від Надавача) ...

проверил там же файлик подписанный agent.js:
Час підпису (підтверджено кваліфікованою позначкою часу для **даних** від Надавача) ...

**Comment by muromec** [comment]
@spyzp  Привіт!

Інтересно, пришліть приклад файла на імейл -- я подивлюсь в чому різниця

**Comment by spyzp** [comment]
отправил файлы и пару ссылочек

**Comment by spyzp** [comment]
byhaem.in.ua

**Comment by pinchukd** [comment]
> спасибо за быстрый ответ

Решили с передачей метки времени для подписи?

У меня вышло решить проблему не передачи метки для документа просто закомментировав одну строчку кода.

Но я еще не знаю передается ли метка в подпись?

**Comment by spyzp** [comment]
@pinchukd, 
все решено давно, можно выбирать какие метки времени ставить, а какие нет при помощи ключа.
убедитесь, что у вас последняя версия, и посмотрите в README.

**Comment by pinchukd** [comment]
Спасибо, у меня был другая библиотека, теперь увидел в документации к вашей.
