### ISSUE TITLE
Підпис хеша файлу

### ISSUE THREAD

**Issue by AliceSkilsara** [dstucrypt/agent#42]
Доброго дня! Дякую вам за Вашу роботу! Підкажіть будь-ласка, чи є така можливість, підписувати тільки хеш файла? оскільки меня потрібно підписувати досить великі файли, то хочу відокремити підпис від файлу. Дякую!

**Comment by muromec** [comment]
День добрий. Є така можливість, подивіться `--detached` в рідмі.
