### ISSUE TITLE
Работа без интернет соединения

### ISSUE THREAD

**Issue by MagGr** [dstucrypt/agent#56]
Спасибо Вам за ваш проект! Подскажите пожалуйста есть ли возможность подписывать документы без соединения с интернентом?  
Выполняю команду
node C:\agent-master\index.js --sign --key privatPart.dat:XXX  --input input.tmp --output output.tmp.p7s --no-tax --tsp signature --cert publicPart.cer --role personal 
Если соединение с интрнетом есть, все работает отлично! 
Если же интернета нет, то получаю ошибку. 
typeError:cannot read property of null (reading 'constructor') 
at C:\agent-master\index.js:21:14 
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by MagGr** [comment]
Вопрос снят. Обращение к интернет ресурсам (и соотвевенно ошибка) идет только если используется метка времени (параметр --tsp) Для моей задачи, как оказалось, она не нужна. Убрав параметр  я tsp успешно подписываю как при наличии соединения, так и при его отсутвии.

**Comment by muromec** [comment]
Дякую!

**Comment by muromec** [comment]
close
